# 2023-12-28T19:42:33.495403+00:00
# Level 1
pip install "absl-py>=1.4.0"
pip install "addict>=2.4.0"
pip install "aenum>=3.1.15"
pip install "affine>=2.4.0"
pip install "affinegap>=1.12"
pip install "aiofiles>=22.1.0"
pip install "aiosqlite>=0.19.0"
pip install "alabaster>=0.7.13"
pip install "altgraph>=0.17.4"
pip install "annotated-types>=0.6.0"
pip check
pip install "ansi2html>=1.8.0"
pip install "ansicon>=1.89.0"
pip install "antlr4-python3-runtime>=4.9.3"
pip install "appdirs>=1.4.4"
pip install "appnope>=0.1.3"
pip install "argcomplete>=3.1.6"
pip install "asciitree>=0.3.3"
pip install "asgiref>=3.7.2"
pip install "asn1crypto>=1.5.1"
pip install "ast-decompiler>=0.7.0"
pip check
pip install "astor>=0.8.1"
pip install "async-generator>=1.10"
pip install "async-lru>=2.0.4"
pip install "async-timeout>=4.0.3"
pip install "asynctest>=0.13.0"
pip install "atomicwrites>=1.4.1"
pip install "attrs>=23.1.0"
pip install "audioread>=3.0.1"
pip install "azure-common>=1.1.28"
pip check
pip install "babel>=2.13.1"
pip install "backcall>=0.2.0"
pip install "backoff>=1.10.0"
pip install "base58>=2.1.1"
pip install "bcrypt>=4.0.1"
pip install "billiard>=4.2.0"
pip install "blinker>=1.7.0"
pip install "blurhash>=1.1.4"
pip install "boltons>=23.1.1"
pip install "brotli>=1.1.0"
pip check
pip install "cachetools>=5.3.2"
pip install "catalogue>=2.0.10"
pip install "cchardet>=2.1.7"
pip install "certifi>=2023.7.22"
pip install "chardet>=5.2.0"
pip install "charset-normalizer>=3.3.2"
pip install "chess>=1.10.0"
pip install "clang>=16.0.1.1"
pip install "click>=8.1.7"
pip install "cloudpathlib>=0.16.0"
pip check
pip install "cloudpickle>=2.2.1"
pip install "cmake>=3.27.7"
pip install "codemod>=1.0.0"
pip install "colorama>=0.4.6"
pip install "colorful>=0.5.5"
pip install "colorlover>=0.3.0"
pip install "commonmark>=0.9.1"
pip install "configargparse>=1.7"
pip install "configparser>=6.0.0"
pip install "confluent-kafka>=2.3.0"
pip check
pip install "conllu>=4.5.3"
pip install "contextlib2>=21.6.0"
pip install "coverage>=7.3.2"
pip install "cramjam>=2.7.0"
pip install "crashtest>=0.3.1"
pip install "crcmod>=1.7"
pip install "cvxopt>=1.3.2"
pip install "cwcwidth>=0.1.9"
pip install "cycler>=0.12.1"
pip install "cymem>=2.0.8"
pip check
pip install "cypari>=2.5.4"
pip install "cython>=3.0.5"
pip check
pip install "dacite>=1.8.1"
pip install "dacktool>=0.0.7"
pip install "dash-core-components>=2.0.0"
pip install "dash-html-components>=2.0.0"
pip install "dash-renderer>=1.9.1"
pip install "dash-table>=5.0.0"
pip install "dbt-extractor>=0.5.0"
pip install "debugpy>=1.8.0"
pip install "decorator>=4.4.2"
pip install "defusedxml>=0.7.1"
pip check
pip install "dill>=0.3.7"
pip install "distlib>=0.3.7"
pip install "distro>=1.8.0"
pip install "dlib>=19.24.2"
pip install "dm-tree>=0.1.8"
pip install "dnspython>=2.4.2"
pip install "docutils>=0.17.1"
pip check
pip install "easydict>=1.11"
pip install "easyprocess>=1.1"
pip install "editdistance>=0.6.2"
pip install "einops>=0.7.0"
pip install "emoji>=2.8.0"
pip install "entrypoint2>=1.1"
pip install "entrypoints>=0.4"
pip install "ephem>=4.1.5"
pip install "et-xmlfile>=1.1.0"
pip install "etils>=1.5.2"
pip check
pip install "exceptiongroup>=1.1.3"
pip install "executing>=2.0.1"
pip check
pip install "face-recognition-models>=0.3.0"
pip install "faiss-cpu>=1.7.4"
pip install "fake-useragent>=1.3.0"
pip install "farama-notifications>=0.0.4"
pip install "fast-ctc-decode>=0.3.5"
pip install "fastavro>=1.9.0"
pip install "fasteners>=0.19"
pip install "fastjsonschema>=2.19.0"
pip install "fastprogress>=1.0.3"
pip install "fastrlock>=0.8.2"
pip check
pip install "ffmpy>=0.3.1"
pip install "filelock>=3.13.1"
pip install "flatbuffers>=23.5.26"
pip install "fonttools>=4.44.3"
pip install "fqdn>=1.5.1"
pip install "freetype-py>=2.4.0"
pip install "frozendict>=2.3.8"
pip install "frozenlist>=1.4.0"
pip install "fsspec>=2023.10.0"
pip install "funcy>=2.0"
pip check
pip install "future>=0.18.3"
pip check
pip install "gast>=0.5.4"
pip install "geographiclib>=2.0"
pip install "gin-config>=0.5.0"
pip install "git-lfs>=1.6"
pip install "glib>=1.0.0"
pip install "glob2>=0.7"
pip install "google-crc32c>=1.5.0"
pip install "googledrivedownloader>=0.4"
pip install "gprof2dot>=2022.7.29"
pip install "gputil>=1.4.0"
pip check
pip install "graphviz>=0.20.1"
pip install "greenlet>=3.0.1"
pip install "grpcio>=1.59.2"
pip install "gym-notices>=0.0.8"
pip check
pip install "h11>=0.14.0"
pip install "haversine>=2.8.0"
pip install "heapdict>=1.0.1"
pip install "hijri-converter>=2.3.1"
pip install "hiredis>=2.2.3"
pip install "hsluv>=5.0.4"
pip install "htmlmin>=0.1.12"
pip install "httpimport>=1.3.1"
pip install "humanfriendly>=10.0"
pip install "humanize>=4.8.0"
pip check
pip install "hupper>=1.12"
pip check
pip install "icu>=0.0.1"
pip install "idna>=3.4"
pip install "imagesize>=1.4.1"
pip install "immutabledict>=3.0.0"
pip install "importlib-resources>=6.1.1"
pip install "imutils>=0.5.4"
pip install "iniconfig>=2.0.0"
pip install "intel-openmp>=2023.0.0"
pip install "ipython-genutils>=0.2.0"
pip install "iso8601>=2.1.0"
pip check
pip install "itsdangerous>=2.1.2"
pip check
pip install "jdcal>=1.4.1"
pip install "jeepney>=0.8.0"
pip install "jieba>=0.42.1"
pip install "jinxed>=1.2.0"
pip install "jmespath>=1.0.1"
pip install "joblib>=1.3.2"
pip install "json-rpc>=1.15.0"
pip install "json5>=0.9.14"
pip install "jsonpickle>=3.0.2"
pip install "jsonpointer>=2.4"
pip check
pip install "jstyleson>=0.0.2"
pip install "jupyterlab-pygments>=0.2.2"
pip install "jupyterlab-widgets>=3.0.9"
pip check
pip install "kaleido>=0.2.1"
pip install "keras>=2.15.0"
pip install "kiwisolver>=1.4.5"
pip install "korean-lunar-calendar>=0.3.1"
pip check
pip install "langcodes>=3.3.0"
pip install "lazy-loader>=0.3"
pip install "levenshtein-search>=1.4.6"
pip install "libclang>=16.0.6"
pip install "llvmlite>=0.41.1"
pip install "lmdb>=1.4.1"
pip install "locket>=1.0.0"
pip install "lockfile>=0.12.2"
pip install "logbook>=1.7.0"
pip install "lxml>=4.9.3"
pip check
pip install "lz4>=4.3.2"
pip check
pip install "markdown>=3.5.1"
pip install "markdown2>=2.4.10"
pip install "markupsafe>=2.1.3"
pip install "mccabe>=0.7.0"
pip install "mdurl>=0.1.2"
pip install "mistune>=3.0.2"
pip install "mock>=5.1.0"
pip install "monotonic>=1.6"
pip install "more-itertools>=10.1.0"
pip install "mpmath>=1.3.0"
pip check
pip install "msgpack>=1.0.7"
pip install "msgpack-python>=0.5.6"
pip install "mss>=9.0.1"
pip install "multidict>=6.0.4"
pip install "multimethod>=1.10"
pip install "multipledispatch>=1.0.0"
pip install "multitasking>=0.0.11"
pip install "munch>=4.0.0"
pip install "murmurhash>=1.0.10"
pip install "mypy-extensions>=1.0.0"
pip check
pip install "natsort>=8.4.0"
pip install "ndindex>=1.7"
pip install "nest-asyncio>=1.5.8"
pip install "netifaces>=0.11.0"
pip install "netron>=7.2.9"
pip install "networkx>=3.2.1"
pip install "ninja>=1.11.1.1"
pip install "numpy>=1.26.2"
pip install "nvidia-ml-py>=12.535.133"
pip check
pip install "oauthlib>=3.2.2"
pip install "okgrade>=0.4.3"
pip install "olefile>=0.46"
pip install "opencensus-context>=0.1.3"
pip install "openvino-telemetry>=2023.2.1"
pip install "optional-django>=0.1.0"
pip install "orjson>=3.9.10"
pip install "overrides>=7.4.0"
pip check
pip install "packaging>=23.2"
pip install "pafy>=0.5.5"
pip install "palettable>=3.3.3"
pip install "pandocfilters>=1.5.0"
pip install "param>=2.0.1"
pip install "parsedatetime>=2.6"
pip install "parso>=0.8.3"
pip install "pastedeploy>=3.0.1"
pip install "pastel>=0.2.1"
pip install "pathlib>=1.0.1"
pip check
pip install "pathspec>=0.11.2"
pip install "pathtools>=0.1.2"
pip install "peewee>=3.17.0"
pip install "pefile>=2023.2.7"
pip install "pep517>=0.13.1"
pip install "persist-queue>=0.8.1"
pip install "pickleshare>=0.7.5"
pip install "pillow>=10.0.1"
pip install "pip>=23.3.1"
pip install "pipdeptree>=2.13.1"
pip check
pip install "plaster>=1.1.2"
pip install "platformdirs>=3.11.0"
pip install "pluggy>=1.3.0"
pip install "plumbum>=1.8.2"
pip install "ply>=3.11"
pip install "portalocker>=2.8.2"
pip install "progress>=1.6"
pip install "prometheus-client>=0.18.0"
pip install "protobuf>=3.20.3"
pip install "psutil>=5.9.6"
pip check
pip install "psycopg2-binary>=2.9.9"
pip install "ptyprocess>=0.7.0"
pip install "pulp>=2.7.0"
pip install "pure-eval>=0.2.2"
pip install "py>=1.11.0"
pip install "py-cpuinfo>=9.0.0"
pip install "py-params>=0.10.2"
pip install "py-spy>=0.3.14"
pip install "py4j>=0.10.9.7"
pip install "pyarrow-hotfix>=0.5"
pip check
pip install "pyasn1>=0.5.0"
pip install "pybind11>=2.11.1"
pip install "pybullet>=3.2.5"
pip install "pycairo>=1.25.1"
pip install "pyclipper>=1.3.0.post3"
pip install "pycodestyle>=2.11.1"
pip install "pycparser>=2.21"
pip install "pycryptodome>=3.19.0"
pip install "pycryptodomex>=3.19.0"
pip install "pydeprecate>=0.3.2"
pip check
pip install "pydicom>=2.4.3"
pip install "pydub>=0.25.1"
pip install "pyflakes>=3.1.0"
pip install "pygame>=2.5.2"
pip install "pygments>=2.16.1"
pip install "pyinstaller-hooks-contrib>=2023.10"
pip install "pyjwt>=2.8.0"
pip install "pylev>=1.4.0"
pip install "pyluach>=2.2.0"
pip install "pymeeus>=0.5.12"
pip check
pip install "pymsgbox>=1.0.9"
pip install "pymysql>=1.1.0"
pip install "pynvml>=11.5.0"
pip install "pyobjc-core>=10.0"
pip install "pyodbc>=5.0.1"
pip install "pyopengl>=3.1.7"
pip install "pyotp>=2.9.0"
pip install "pyparsing>=3.1.1"
pip install "pyperclip>=1.8.2"
pip install "pypng>=0.20220715.0"
pip check
pip install "pyproject-hooks>=1.0.0"
pip install "pyqt6-qt6>=6.6.0"
pip install "pyqt6-sip>=13.6.0"
pip install "pyreadline3>=3.4.1"
pip install "pyrect>=0.2.0"
pip install "pyro-api>=0.1.2"
pip install "pyrsistent>=0.20.0"
pip install "pysimdjson>=5.0.2"
pip install "pysimplegui>=4.60.5"
pip install "pysocks>=1.7.1"
pip check
pip install "pystache>=0.6.5"
pip install "python-barcode>=0.15.1"
pip install "python-dotenv>=1.0.0"
pip install "python-editor>=1.0.4"
pip install "python-gflags>=3.1.2"
pip install "python-json-logger>=2.0.7"
pip install "python-magic>=0.4.27"
pip install "python-socks>=2.4.3"
pip install "pytimeparse>=1.1.8"
pip install "pytweening>=1.0.7"
pip check
pip install "pytz>=2023.3"
pip install "pyyaml>=6.0.1"
pip install "pyzmq>=25.1.1"
pip check
pip install "qcore>=1.10.0"
pip install "redis>=5.0.1"
pip install "regex>=2023.10.3"
pip install "rfc3986>=2.0.0"
pip install "rfc3986-validator>=0.1.1"
pip install "rpds-py>=0.13.0"
pip install "rtree>=1.1.0"
pip install "ruamel-yaml-clib>=0.2.8"
pip install "rubicon-objc>=0.4.7"
pip check
pip install "safetensors>=0.4.0"
pip install "schedule>=1.2.1"
pip install "send2trash>=1.8.2"
pip install "sentencepiece>=0.1.99"
pip install "setproctitle>=1.3.3"
pip install "setuptools>=68.2.2"
pip install "setuptools-git>=1.2"
pip install "shellingham>=1.5.4"
pip install "shortuuid>=1.0.11"
pip install "simpervisor>=1.0.0"
pip check
pip install "simplejson>=3.19.2"
pip install "six>=1.16.0"
pip install "slicer>=0.0.7"
pip install "smart-open>=6.4.0"
pip install "smmap>=5.0.1"
pip install "sniffio>=1.3.0"
pip install "snowballstemmer>=2.2.0"
pip install "sortedcontainers>=2.4.0"
pip install "soupsieve>=2.5"
pip install "spacy-legacy>=3.0.12"
pip check
pip install "spacy-loggers>=1.0.5"
pip install "sphinxcontrib-applehelp>=1.0.4"
pip install "sphinxcontrib-devhelp>=1.0.2"
pip install "sphinxcontrib-htmlhelp>=2.0.1"
pip install "sphinxcontrib-jsmath>=1.0.1"
pip install "sphinxcontrib-qthelp>=1.0.3"
pip install "sphinxcontrib-serializinghtml>=1.1.5"
pip install "sqlparse>=0.4.4"
pip install "stdlib-list>=0.9.0"
pip install "subprocess32>=3.5.4"
pip check
pip install "tabulate>=0.9.0"
pip install "tangled-up-in-unicode>=0.2.0"
pip install "tbb>=2021.5.0"
pip install "tblib>=3.0.0"
pip install "tenacity>=8.2.3"
pip install "tensorboard-data-server>=0.7.2"
pip install "tensorboard-plugin-wit>=1.8.1"
pip install "tensorflow-estimator>=2.15.0"
pip install "tensorflow-gcs-config>=2.14.0"
pip install "tensorflow-io-gcs-filesystem>=0.34.0"
pip check
pip install "termcolor>=2.3.0"
pip install "termcolor-whl>=1.1.3"
pip install "testpath>=0.6.0"
pip install "text-unidecode>=1.3"
pip install "texttable>=1.7.0"
pip install "threadpoolctl>=3.2.0"
pip install "tinydb>=4.8.0"
pip install "toml>=0.10.2"
pip install "tomli>=2.0.1"
pip install "tomlkit>=0.12.3"
pip check
pip install "toolz>=0.12.0"
pip install "torchsummary>=1.5.1"
pip install "tornado>=6.3.3"
pip install "tqdm>=4.66.1"
pip install "traitlets>=5.13.0"
pip install "translationstring>=1.4"
pip install "typed-ast>=1.5.5"
pip install "types-python-dateutil>=2.8.19.14"
pip install "types-pytz>=2023.3.1.1"
pip install "types-pyyaml>=6.0.12.12"
pip check
pip install "typing-extensions>=4.8.0"
pip install "tzdata>=2023.3"
pip install "tzlocal>=5.2"
pip check
pip install "ua-parser>=0.18.0"
pip install "uc-micro-py>=1.0.2"
pip install "ujson>=5.8.0"
pip install "unidecode>=1.3.7"
pip install "uri-template>=1.3.0"
pip install "uritemplate>=4.1.1"
pip install "urllib3>=2.0.7"
pip install "uuid>=1.30"
pip check
pip install "validators>=0.22.0"
pip install "venusian>=3.1.0"
pip install "vine>=5.1.0"
pip check
pip install "waitress>=2.1.2"
pip install "wasabi>=1.1.2"
pip install "watchdog>=3.0.0"
pip install "wcwidth>=0.2.10"
pip install "webcolors>=1.13"
pip install "webencodings>=0.5.1"
pip install "webob>=1.8.7"
pip install "websocket-client>=1.6.4"
pip install "websockets>=12.0"
pip install "wheel>=0.41.3"
pip check
pip install "widgetsnbextension>=4.0.9"
pip install "wincertstore>=0.2"
pip install "wireless>=0.3.3"
pip install "wrapt>=1.16.0"
pip check
pip install "xlrd>=2.0.1"
pip install "xlsxwriter>=3.1.9"
pip install "xlwt>=1.3.0"
pip install "xxhash>=3.4.1"
pip install "xyzservices>=2023.10.1"
pip check
pip install "y-py>=0.6.2"
pip install "youtube-dl>=2021.12.17"
pip check
pip install "zict>=3.0.0"
pip install "zipp>=3.17.0"
pip install "zstd>=1.5.5.1"
pip check
# Level 1
# Level 2
pip install "accessible-pygments>=0.0.4"
pip install "aioredis>=2.0.1"
pip install "aiosignal>=1.3.1"
pip install "amqp>=5.2.0"
pip install "anyio>=3.7.1"
pip install "array-record>=0.4.1"
pip install "asttokens>=2.4.1"
pip install "astunparse>=1.6.3"
pip install "asynq>=1.5.1"
pip install "atari-py>=0.3.0"
pip check
pip install "autograd>=1.6.2"
pip install "autopep8>=2.0.4"
pip check
pip install "beautifulsoup4>=4.12.2"
pip install "biopython>=1.81"
pip install "black>=23.11.0"
pip install "bleach>=6.1.0"
pip install "blessed>=1.20.0"
pip install "blessings>=1.7"
pip install "blis>=0.7.11"
pip install "blosc2>=2.3.1"
pip install "bottleneck>=1.3.7"
pip install "build>=1.0.3"
pip check
pip install "casadi>=3.6.4"
pip install "categorical-distance>=1.9"
pip install "cattrs>=23.1.2"
pip install "cffi>=1.16.0"
pip install "cftime>=1.6.3"
pip install "click-didyoumean>=0.3.0"
pip install "click-plugins>=1.1.1"
pip install "cligj>=0.7.2"
pip install "clikit>=0.6.2"
pip install "coloredlogs>=15.0.1"
pip check
pip install "colormath>=3.0.0"
pip install "comm>=0.2.0"
pip install "contourpy>=1.2.0"
pip install "convertdate>=2.4.0"
pip check
pip install "deprecated>=1.2.14"
pip install "deprecation>=2.1.0"
pip install "django>=4.2.7"
pip install "docker-pycreds>=0.4.0"
pip check
pip install "elastic-transport>=8.10.0"
pip install "email-validator>=2.1.0"
pip install "eventkit>=1.0.1"
pip check
pip install "face-recognition>=1.3.0"
pip install "fastcluster>=1.2.6"
pip install "fastcore>=1.5.29"
pip install "fastdtw>=0.3.4"
pip install "fire>=0.5.0"
pip install "flake8>=6.1.0"
pip install "fs>=2.4.16"
pip install "ftfy>=6.1.1"
pip check
pip install "geopy>=2.4.0"
pip install "gitdb>=4.0.11"
pip install "glog>=0.3.1"
pip install "google-pasta>=0.2.0"
pip install "google-resumable-media>=2.6.0"
pip install "googleapis-common-protos>=1.61.0"
pip install "gunicorn>=21.2.0"
pip install "gym>=0.26.2"
pip install "gymnasium>=0.29.1"
pip check
pip install "h5py>=3.10.0"
pip install "html5lib>=1.1"
pip install "httpcore>=1.0.2"
pip install "httplib2>=0.22.0"
pip install "hypothesis>=6.89.0"
pip check
pip install "imagecodecs>=2023.9.18"
pip install "imageio>=2.32.0"
pip install "imageio-ffmpeg>=0.4.9"
pip install "imagezmq>=1.1.1"
pip install "importlab>=0.8.1"
pip install "importlib-metadata>=6.8.0"
pip install "intervaltree>=3.1.0"
pip install "isodate>=0.6.1"
pip check
pip install "jaraco-classes>=3.3.0"
pip install "jax-jumpy>=1.0.0"
pip install "jedi>=0.19.1"
pip install "jinja2>=3.1.2"
pip install "jupyter-core>=5.5.0"
pip install "jupyter-ydoc>=0.3.4"
pip check
pip install "keras-preprocessing>=1.1.2"
pip install "leather>=0.3.4"
pip install "lightning-utilities>=0.9.0"
pip install "linkify-it-py>=2.0.2"
pip install "livereload>=2.6.3"
pip install "logical-unification>=0.4.6"
pip check
pip install "m3u8>=3.6.0"
pip install "macholib>=1.16.3"
pip install "mako>=1.3.0"
pip install "markdown-it-py>=3.0.0"
pip install "marshmallow>=3.20.1"
pip install "mashumaro>=3.10"
pip install "matplotlib-inline>=0.1.6"
pip install "memory-profiler>=0.61.0"
pip install "mkl>=2023.2.1"
pip install "ml-dtypes>=0.3.1"
pip check
pip install "mlagents-envs>=0.28.0"
pip install "mouseinfo>=0.1.3"
pip install "multiprocess>=0.70.15"
pip install "mypy>=1.7.0"
pip check
pip install "nibabel>=5.1.0"
pip install "nltk>=3.8.1"
pip install "nodejs>=0.1.1"
pip install "numba>=0.58.1"
pip install "numcodecs>=0.12.1"
pip install "numexpr>=2.8.7"
pip check
pip install "omegaconf>=2.3.0"
pip install "onnx>=1.15.0"
pip install "opencv-contrib-python>=4.8.1.78"
pip install "opencv-python>=4.8.1.78"
pip install "opencv-python-headless>=4.8.1.78"
pip install "openpyxl>=3.1.2"
pip install "openvino>=2023.2.0"
pip install "opt-einsum>=3.3.0"
pip install "oscrypto>=1.3.0"
pip install "outcome>=1.3.0"
pip check
pip install "pandas-stubs>=2.1.1.230928"
pip install "pandoc>=2.3"
pip install "params-flow>=0.8.2"
pip install "parasail>=1.3.4"
pip install "partd>=1.4.1"
pip install "patsy>=0.5.3"
pip install "pexpect>=4.8.0"
pip install "plaster-pastedeploy>=1.0.1"
pip install "plotly>=5.18.0"
pip install "plyfile>=1.0.2"
pip check
pip install "portpicker>=1.6.0"
pip install "preshed>=3.0.9"
pip install "prettytable>=3.9.0"
pip install "proglog>=0.1.10"
pip install "promise>=2.3"
pip install "prompt-toolkit>=3.0.41"
pip install "proto-plus>=1.22.3"
pip install "py-lets-be-rational>=1.0.1"
pip install "pyaml>=23.9.7"
pip install "pyarrow>=14.0.1"
pip check
pip install "pyasn1-modules>=0.3.0"
pip install "pyct>=0.5.0"
pip install "pydantic-core>=2.14.3"
pip install "pydeps>=1.12.17"
pip install "pydot>=1.4.2"
pip install "pyerfa>=2.0.1.1"
pip install "pygetwindow>=0.0.9"
pip install "pymongo>=4.6.0"
pip install "pyobjc-framework-cocoa>=10.0"
pip install "pyperf>=2.6.2"
pip check
pip install "pyqt6>=6.6.0"
pip install "pyquaternion>=0.9.9"
pip install "pyscreenshot>=3.1"
pip install "pyscreeze>=0.1.30"
pip install "pytesseract>=0.3.10"
pip install "pytest>=7.4.3"
pip install "python-bidi>=0.4.2"
pip install "python-daemon>=3.0.1"
pip install "python-dateutil>=2.8.2"
pip install "python-slugify>=8.0.1"
pip check
pip install "python-utils>=3.8.1"
pip install "pytz-deprecation-shim>=0.1.0.post0"
pip install "pyviz-comms>=3.0.0"
pip install "pywavelets>=1.4.1"
pip check
pip install "qrcode>=7.4.2"
pip install "qtpy>=2.4.1"
pip install "querystring-parser>=1.2.4"
pip check
pip install "rawpy>=0.18.1"
pip install "reactivex>=4.0.4"
pip install "referencing>=0.31.0"
pip install "requests>=2.31.0"
pip install "retrying>=1.3.4"
pip install "rfc3339-validator>=0.1.4"
pip install "rsa>=4.9"
pip check
pip install "sacrebleu>=2.3.2"
pip install "sacremoses>=0.1.1"
pip install "scipy>=1.11.3"
pip install "sentry-sdk>=1.35.0"
pip install "setuptools-scm>=8.0.4"
pip install "shapely>=2.0.2"
pip install "simplecosine>=1.2"
pip install "soxr>=0.3.7"
pip install "sphinx-markdown-tables>=0.0.17"
pip install "sqlalchemy>=1.4.50"
pip check
pip install "srsly>=2.4.8"
pip install "stanio>=0.3.0"
pip install "streamz>=0.6.4"
pip install "sympy>=1.12"
pip check
pip install "tensorboardx>=2.6.2.2"
pip install "tensorflow-hub>=0.15.0"
pip install "terminado>=0.18.0"
pip install "tifffile>=2023.9.26"
pip install "tinycss2>=1.2.1"
pip install "typeguard>=4.1.5"
pip install "typer>=0.9.0"
pip install "typeshed-client>=2.4.0"
pip install "typing-inspect>=0.9.0"
pip check
pip install "uamqp>=1.6.6"
pip install "url-normalize>=1.4.3"
pip install "userpath>=1.9.1"
pip install "uvicorn>=0.24.0"
pip check
pip install "virtualenv>=20.24.6"
pip install "vispy>=0.14.1"
pip check
pip install "werkzeug>=3.0.1"
pip install "wsproto>=1.2.0"
pip check
pip install "yarl>=1.9.2"
pip install "yaspin>=3.0.1"
pip install "ypy-websocket>=0.8.4"
pip check
pip install "zope-deprecation>=5.0"
pip install "zope-interface>=6.1"
pip check
# Level 2
# Level 3
pip install "agate>=1.9.0"
pip install "aiohttp>=3.8.6"
pip install "alembic>=1.12.1"
pip install "analytics-python>=1.4.0"
pip install "argon2-cffi-bindings>=21.2.0"
pip install "arrow>=1.3.0"
pip install "astropy>=5.3.4"
pip install "azure-core>=1.29.5"
pip check
pip install "botocore>=1.32.2"
pip install "branca>=0.7.0"
pip install "brotlipy>=0.7.0"
pip install "bs4>=0.0.1"
pip check
pip install "cachecontrol>=0.13.1"
pip install "cairocffi>=1.6.1"
pip install "clarabel>=0.6.0"
pip install "click-repl>=0.3.0"
pip install "coinpaprika>=0.1.0"
pip install "colorcet>=3.0.1"
pip install "comcrawl>=1.0.2"
pip install "cons>=0.4.6"
pip install "coremltools>=7.1"
pip install "croniter>=2.0.1"
pip check
pip install "cryptography>=41.0.5"
pip install "cssselect2>=0.7.0"
pip install "curtsies>=0.4.2"
pip check
pip install "dask>=2023.11.0"
pip install "databricks-cli>=0.18.0"
pip install "datashape>=0.5.2"
pip install "datetime>=5.3"
pip install "datetime-distance>=0.1.3"
pip install "django-cors-headers>=4.3.1"
pip install "django-extensions>=3.2.3"
pip install "django-http-exceptions>=1.4.0"
pip install "django-model-utils>=4.3.1"
pip install "django-request-logging>=0.7.5"
pip check
pip install "djangorestframework>=3.14.0"
pip install "docker>=6.1.3"
pip check
pip install "ecos>=2.0.12"
pip install "elasticsearch>=8.11.0"
pip check
pip install "feather-format>=0.4.1"
pip install "flask>=3.0.0"
pip check
pip install "gdown>=4.7.1"
pip install "gensim>=4.3.2"
pip install "gitpython>=3.1.40"
pip install "google>=3.0.0"
pip install "google-auth>=2.23.4"
pip install "googletransx>=2.4.2"
pip install "gpustat>=1.1.1"
pip install "grpc-google-iam-v1>=0.12.7"
pip install "grpcio-status>=1.48.1"
pip check
pip install "h2o>=3.44.0.2"
pip install "h5netcdf>=1.3.0"
pip install "holidays>=0.36"
pip install "httplib2shim>=0.0.3"
pip install "httpx>=0.25.1"
pip install "huggingface-hub>=0.19.4"
pip install "hyperopt>=0.2.7"
pip check
pip install "ib-insync>=0.9.86"
pip install "imagecodecs-lite>=2022.9.26"
pip install "imagehash>=4.3.1"
pip install "influxdb-client>=1.38.0"
pip install "int-date>=0.2.0"
pip install "intrinio-sdk>=6.26.2"
pip check
pip install "jax>=0.4.20"
pip install "jsonschema-specifications>=2023.11.1"
pip install "jupyter-client>=8.6.0"
pip install "jupyter-packaging>=0.12.3"
pip install "jupyter-server-terminals>=0.4.4"
pip check
pip install "kaggle>=1.5.16"
pip install "kivy-garden>=0.1.5"
pip check
pip install "libcst>=1.1.0"
pip install "lightgbm>=4.1.0"
pip install "luigi>=3.4.0"
pip install "lunarcalendar>=0.0.9"
pip check
pip install "mastodon-py>=1.8.1"
pip install "matplotlib>=3.8.1"
pip install "mdit-py-plugins>=0.4.0"
pip install "miniful>=0.0.6"
pip install "minimal-snowplow-tracker>=0.0.2"
pip install "mixpanel>=4.10.0"
pip install "moviepy>=1.0.3"
pip check
pip install "netcdf4>=1.6.5"
pip install "oauth2client>=4.1.3"
pip install "onnxconverter-common>=1.13.0"
pip install "onnxoptimizer>=0.3.13"
pip install "onnxruntime>=1.16.2"
pip check
pip install "pandas>=2.1.3"
pip install "pathy>=0.10.3"
pip install "persistent>=5.1"
pip install "pettingzoo>=1.24.2"
pip install "pip-tools>=7.3.0"
pip install "pipx>=1.2.1"
pip install "pooch>=1.8.0"
pip install "progressbar2>=4.2.0"
pip install "pyanalyze>=0.11.0"
pip install "pycares>=4.4.0"
pip check
pip install "pydantic>=2.5.1"
pip install "pynacl>=1.5.0"
pip install "pyobjc-framework-accounts>=10.0"
pip install "pyobjc-framework-addressbook>=10.0"
pip install "pyobjc-framework-adservices>=10.0"
pip install "pyobjc-framework-adsupport>=10.0"
pip install "pyobjc-framework-applescriptkit>=10.0"
pip install "pyobjc-framework-applescriptobjc>=10.0"
pip install "pyobjc-framework-apptrackingtransparency>=10.0"
pip install "pyobjc-framework-audiovideobridging>=10.0"
pip check
pip install "pyobjc-framework-authenticationservices>=10.0"
pip install "pyobjc-framework-automaticassessmentconfiguration>=10.0"
pip install "pyobjc-framework-automator>=10.0"
pip install "pyobjc-framework-avrouting>=10.0"
pip install "pyobjc-framework-backgroundassets>=10.0"
pip install "pyobjc-framework-businesschat>=10.0"
pip install "pyobjc-framework-calendarstore>=10.0"
pip install "pyobjc-framework-callkit>=10.0"
pip install "pyobjc-framework-cfnetwork>=10.0"
pip install "pyobjc-framework-classkit>=10.0"
pip check
pip install "pyobjc-framework-collaboration>=10.0"
pip install "pyobjc-framework-colorsync>=10.0"
pip install "pyobjc-framework-contacts>=10.0"
pip install "pyobjc-framework-coreaudio>=10.0"
pip install "pyobjc-framework-corebluetooth>=10.0"
pip install "pyobjc-framework-coredata>=10.0"
pip install "pyobjc-framework-corehaptics>=10.0"
pip install "pyobjc-framework-corelocation>=10.0"
pip install "pyobjc-framework-coremedia>=10.0"
pip install "pyobjc-framework-coremediaio>=10.0"
pip check
pip install "pyobjc-framework-coremidi>=10.0"
pip install "pyobjc-framework-coreml>=10.0"
pip install "pyobjc-framework-coremotion>=10.0"
pip install "pyobjc-framework-corespotlight>=10.0"
pip install "pyobjc-framework-corewlan>=10.0"
pip install "pyobjc-framework-cryptotokenkit>=10.0"
pip install "pyobjc-framework-datadetection>=10.0"
pip install "pyobjc-framework-devicecheck>=10.0"
pip install "pyobjc-framework-discrecording>=10.0"
pip install "pyobjc-framework-diskarbitration>=10.0"
pip check
pip install "pyobjc-framework-dvdplayback>=10.0"
pip install "pyobjc-framework-eventkit>=10.0"
pip install "pyobjc-framework-exceptionhandling>=10.0"
pip install "pyobjc-framework-executionpolicy>=10.0"
pip install "pyobjc-framework-extensionkit>=10.0"
pip install "pyobjc-framework-externalaccessory>=10.0"
pip install "pyobjc-framework-fileprovider>=10.0"
pip install "pyobjc-framework-findersync>=10.0"
pip install "pyobjc-framework-fsevents>=10.0"
pip install "pyobjc-framework-gamecenter>=10.0"
pip check
pip install "pyobjc-framework-gamecontroller>=10.0"
pip install "pyobjc-framework-healthkit>=10.0"
pip install "pyobjc-framework-imagecapturecore>=10.0"
pip install "pyobjc-framework-imserviceplugin>=9.2"
pip install "pyobjc-framework-inputmethodkit>=10.0"
pip install "pyobjc-framework-installerplugins>=10.0"
pip install "pyobjc-framework-intents>=10.0"
pip install "pyobjc-framework-iobluetooth>=10.0"
pip install "pyobjc-framework-iosurface>=10.0"
pip install "pyobjc-framework-ituneslibrary>=10.0"
pip check
pip install "pyobjc-framework-kernelmanagement>=10.0"
pip install "pyobjc-framework-latentsemanticmapping>=10.0"
pip install "pyobjc-framework-mailkit>=10.0"
pip install "pyobjc-framework-mediaaccessibility>=10.0"
pip install "pyobjc-framework-mediatoolbox>=10.0"
pip install "pyobjc-framework-metal>=10.0"
pip install "pyobjc-framework-metrickit>=10.0"
pip install "pyobjc-framework-mlcompute>=10.0"
pip install "pyobjc-framework-multipeerconnectivity>=10.0"
pip install "pyobjc-framework-naturallanguage>=10.0"
pip check
pip install "pyobjc-framework-netfs>=10.0"
pip install "pyobjc-framework-network>=10.0"
pip install "pyobjc-framework-networkextension>=10.0"
pip install "pyobjc-framework-notificationcenter>=10.0"
pip install "pyobjc-framework-opendirectory>=10.0"
pip install "pyobjc-framework-osakit>=10.0"
pip install "pyobjc-framework-passkit>=10.0"
pip install "pyobjc-framework-pencilkit>=10.0"
pip install "pyobjc-framework-photos>=10.0"
pip install "pyobjc-framework-photosui>=10.0"
pip check
pip install "pyobjc-framework-preferencepanes>=10.0"
pip install "pyobjc-framework-pushkit>=10.0"
pip install "pyobjc-framework-quartz>=10.0"
pip install "pyobjc-framework-replaykit>=10.0"
pip install "pyobjc-framework-safariservices>=10.0"
pip install "pyobjc-framework-screensaver>=10.0"
pip install "pyobjc-framework-screentime>=10.0"
pip install "pyobjc-framework-scriptingbridge>=10.0"
pip install "pyobjc-framework-security>=10.0"
pip install "pyobjc-framework-servicemanagement>=10.0"
pip check
pip install "pyobjc-framework-sharedwithyoucore>=10.0"
pip install "pyobjc-framework-shazamkit>=10.0"
pip install "pyobjc-framework-social>=10.0"
pip install "pyobjc-framework-soundanalysis>=10.0"
pip install "pyobjc-framework-speech>=10.0"
pip install "pyobjc-framework-storekit>=10.0"
pip install "pyobjc-framework-systemconfiguration>=10.0"
pip install "pyobjc-framework-systemextensions>=10.0"
pip install "pyobjc-framework-threadnetwork>=10.0"
pip install "pyobjc-framework-uniformtypeidentifiers>=10.0"
pip check
pip install "pyobjc-framework-usernotifications>=10.0"
pip install "pyobjc-framework-videosubscriberaccount>=10.0"
pip install "pyobjc-framework-virtualization>=10.0"
pip install "pyobjc-framework-webkit>=10.0"
pip install "pyperformance>=1.10.0"
pip install "pyramid>=2.0.2"
pip check
pip install "qdldl>=0.1.7"
pip install "requests-cache>=1.1.0"
pip install "requests-file>=1.5.1"
pip install "requests-oauthlib>=1.3.1"
pip install "requests-toolbelt>=1.0.0"
pip install "requests-unixsocket>=0.3.0"
pip install "resampy>=0.4.2"
pip install "responses>=0.24.1"
pip install "rich>=13.7.0"
pip check
pip install "scikit-image>=0.22.0"
pip install "scikit-learn>=1.3.2"
pip install "sclblpy>=0.1.10"
pip install "scs>=3.2.4"
pip install "simpful>=2.11.0"
pip install "soundfile>=0.12.1"
pip install "sparse>=0.14.0"
pip install "spectra>=0.0.11"
pip install "sphinx>=4.5.0"
pip install "stack-data>=0.6.3"
pip check
pip install "starlette>=0.32.0"
pip install "stumpy>=1.12.0"
pip check
pip install "tables>=3.9.1"
pip install "tensorflow-metadata>=1.14.0"
pip install "textblob>=0.17.1"
pip install "tf-keras-vis>=0.8.6"
pip install "tf2onnx>=1.15.1"
pip install "theano>=1.0.5"
pip install "tiingo>=0.14.0"
pip install "torch>=2.1.1"
pip install "trio>=0.23.1"
pip check
pip install "webargs>=8.3.0"
pip install "wikipedia>=1.4.0"
pip check
pip install "xgboost>=2.0.2"
pip install "yahoofinancials>=1.17"
pip check
pip install "zarr>=2.16.1"
pip check
# Level 3
# Level 4
pip install "aiodns>=3.1.1"
pip install "aiohttp-cors>=0.7.0"
pip install "aiohttp-socks>=0.8.4"
pip install "alpha-vantage>=2.3.1"
pip install "argon2-cffi>=23.1.0"
pip install "authlib>=1.2.1"
pip install "axial-positional-embedding>=0.2.1"
pip install "azure-eventhub>=5.11.5"
pip install "azure-storage-blob>=12.19.0"
pip check
pip install "bokeh>=3.3.1"
pip install "btrees>=5.1"
pip check
pip install "cmdstanpy>=1.2.0"
pip install "confection>=0.1.3"
pip install "control>=0.9.4"
pip check
pip install "daft>=0.1.2"
pip install "dash>=2.14.1"
pip install "datasets>=2.15.0"
pip install "db-dtypes>=1.1.1"
pip install "descartes>=1.1.0"
pip install "diffusers>=0.23.1"
pip install "distributed>=2023.11.0"
pip check
pip install "etuples>=0.3.9"
pip install "exchange-calendars>=4.5"
pip check
pip install "flask-compress>=1.14"
pip install "folium>=0.15.0"
pip install "fst-pso>=1.8.1"
pip check
pip install "geos>=0.2.3"
pip install "google-api-core>=1.34.0"
pip install "google-auth-httplib2>=0.1.1"
pip install "google-auth-oauthlib>=1.1.0"
pip check
pip install "inflect>=7.0.0"
pip install "invisible-watermark>=0.2.0"
pip install "ipython>=8.17.2"
pip install "isoduration>=20.11.0"
pip check
pip install "jsonschema>=4.20.0"
pip install "keras-vis>=0.4.1"
pip install "keras2onnx>=1.7.0"
pip install "kivy>=2.2.1"
pip install "kivy-examples>=2.2.1"
pip install "kmodes>=0.12.2"
pip check
pip install "librosa>=0.10.1"
pip install "lightfm>=1.17"
pip install "local-attention>=1.9.0"
pip check
pip install "matplotlib-venn>=0.11.9"
pip install "mizani>=0.9.2"
pip install "mlflow>=2.8.1"
pip install "mlxtend>=0.23.0"
pip install "mplfinance>=0.12.8b9"
pip install "msrest>=0.7.1"
pip install "music21>=9.1.0"
pip check
pip install "nilearn>=0.10.2"
pip install "nystrom-attention>=0.0.11"
pip check
pip install "onnx-simplifier>=0.4.35"
pip install "openai>=1.3.2"
pip install "osqp>=0.6.3"
pip check
pip install "paramiko>=3.3.1"
pip install "phik>=0.12.3"
pip install "powerlaw>=1.5"
pip install "proj>=0.2.0"
pip install "prometheus-flask-exporter>=0.23.0"
pip install "py-vollib>=1.0.1"
pip install "pyautogui>=0.9.54"
pip install "pycocotools>=2.0.7"
pip install "pydata-sphinx-theme>=0.13.3"
pip install "pygithub>=2.1.1"
pip check
pip install "pyldavis>=3.4.1"
pip install "pynndescent>=0.5.10"
pip install "pyobjc-framework-accessibility>=10.0"
pip install "pyobjc-framework-applicationservices>=10.0"
pip install "pyobjc-framework-avfoundation>=10.0"
pip install "pyobjc-framework-avkit>=10.0"
pip install "pyobjc-framework-cloudkit>=10.0"
pip install "pyobjc-framework-contactsui>=10.0"
pip install "pyobjc-framework-coreaudiokit>=10.0"
pip install "pyobjc-framework-coreservices>=10.0"
pip check
pip install "pyobjc-framework-coretext>=10.0"
pip install "pyobjc-framework-discrecordingui>=10.0"
pip install "pyobjc-framework-fileproviderui>=10.0"
pip install "pyobjc-framework-gamekit>=10.0"
pip install "pyobjc-framework-instantmessage>=10.0"
pip install "pyobjc-framework-intentsui>=10.0"
pip install "pyobjc-framework-iobluetoothui>=10.0"
pip install "pyobjc-framework-linkpresentation>=10.0"
pip install "pyobjc-framework-localauthentication>=10.0"
pip install "pyobjc-framework-mapkit>=10.0"
pip check
pip install "pyobjc-framework-medialibrary>=10.0"
pip install "pyobjc-framework-metalfx>=10.0"
pip install "pyobjc-framework-metalkit>=10.0"
pip install "pyobjc-framework-metalperformanceshaders>=10.0"
pip install "pyobjc-framework-modelio>=10.0"
pip install "pyobjc-framework-oslog>=10.0"
pip install "pyobjc-framework-quicklookthumbnailing>=10.0"
pip install "pyobjc-framework-safetykit>=10.0"
pip install "pyobjc-framework-scenekit>=10.0"
pip install "pyobjc-framework-screencapturekit>=10.0"
pip check
pip install "pyobjc-framework-securityfoundation>=10.0"
pip install "pyobjc-framework-securityinterface>=10.0"
pip install "pyobjc-framework-sharedwithyou>=10.0"
pip install "pyobjc-framework-spritekit>=10.0"
pip install "pyobjc-framework-syncservices>=10.0"
pip install "pyobjc-framework-usernotificationsui>=10.0"
pip install "pyobjc-framework-videotoolbox>=10.0"
pip install "pyobjc-framework-vision>=10.0"
pip install "pyod>=1.1.1"
pip install "pyopenssl>=23.3.0"
pip check
pip install "pyro-ppl>=1.8.6"
pip install "pytorch-ranger>=0.1.1"
pip check
pip install "qudida>=0.0.4"
pip install "rapids>=0.0.1"
pip check
pip install "s3transfer>=0.7.0"
pip install "scikit-plot>=0.3.7"
pip install "seaborn>=0.13.0"
pip install "secretstorage>=3.3.3"
pip install "seqeval>=1.2.2"
pip install "shap>=0.43.0"
pip install "sklearn>=0.0"
pip install "sklearn-pandas>=2.2.0"
pip install "snapml>=1.14.2"
pip install "sphinx-autobuild>=2021.3.14"
pip check
pip install "sphinx-autodoc-typehints>=1.19.1"
pip install "sphinx-panels>=0.6.0"
pip install "sphinxcontrib-jquery>=4.1"
pip install "stable-baselines3>=2.2.0"
pip install "stanza>=1.6.1"
pip install "statsmodels>=0.14.0"
pip install "stockstats>=0.6.2"
pip install "sweetviz>=2.3.0"
pip check
pip install "tensorflow-datasets>=4.9.3"
pip install "tokenizers>=0.15.0"
pip install "torchmetrics>=1.2.0"
pip install "torchvision>=0.16.1"
pip install "trading-calendars>=2.1.1"
pip install "trio-websocket>=0.11.1"
pip install "tweepy>=4.14.0"
pip check
pip install "vega-datasets>=0.9.0"
pip install "visions>=0.7.5"
pip check
pip install "wandb>=0.16.0"
pip install "wordcloud>=1.9.2"
pip install "wrds>=3.1.6"
pip check
pip install "xarray>=2023.10.1"
pip install "yellowbrick>=1.5"
pip install "yfinance>=0.2.31"
pip check
pip install "zeep>=4.2.1"
pip check
# Level 4
# Level 5
pip install "albumentations>=1.3.1"
pip install "altair>=5.1.2"
pip check
pip install "boto3>=1.29.2"
pip install "category-encoders>=2.6.3"
pip install "cornac>=1.17.0"
pip install "cvxpy>=1.4.1"
pip check
pip install "dash-ag-grid>=2.4.0"
pip install "dask-glm>=0.3.1"
pip check
pip install "easyocr>=1.7.1"
pip install "google-api-python-client>=2.99.0"
pip install "google-cloud-bigquery-storage>=2.19.1"
pip install "google-cloud-core>=2.3.3"
pip install "google-cloud-language>=2.11.1"
pip install "gspread>=5.12.0"
pip check
pip install "ipykernel>=6.26.0"
pip install "ipywidgets>=8.1.1"
pip check
pip install "jupyter-events>=0.9.0"
pip install "minikanren>=1.0.3"
pip install "missingno>=0.5.2"
pip check
pip install "nbformat>=5.9.2"
pip install "pandas-market-calendars>=4.3.1"
pip install "panel>=1.3.1"
pip install "plotnine>=0.12.4"
pip install "pmdarima>=2.0.4"
pip install "prophet>=1.1.5"
pip install "pydata-google-auth>=1.8.2"
pip install "pyfume>=0.2.25"
pip install "pyobjc-framework-dictionaryservices>=10.0"
pip install "pyobjc-framework-gameplaykit>=10.0"
pip check
pip install "pyobjc-framework-launchservices>=10.0"
pip install "pyobjc-framework-localauthenticationembeddedui>=10.0"
pip install "pyobjc-framework-mediaplayer>=10.0"
pip install "pyobjc-framework-metalperformanceshadersgraph>=10.0"
pip install "pyobjc-framework-phase>=10.0"
pip install "pyobjc-framework-searchkit>=10.0"
pip install "pytorch-lightning>=2.1.2"
pip install "pywhatkit>=5.4"
pip check
pip install "rapidminer>=10.0.0.0"
pip install "selenium>=4.15.2"
pip install "sphinx-rtd-theme>=1.3.0"
pip install "sshtunnel>=0.4.0"
pip check
pip install "tensorboard>=2.15.1"
pip install "thinc>=8.2.1"
pip install "torch-optimizer>=0.3.0"
pip install "transformers>=4.35.2"
pip install "twint>=2.1.20"
pip check
pip install "umap-learn>=0.5.4"
pip install "weasel>=0.3.4"
pip check
pip install "xarray-einstats>=0.6.0"
pip install "zope-index>=6.0"
pip check
# Level 5
# Level 6
pip install "dask-ml>=2023.3.24"
pip check
pip install "google-cloud-firestore>=2.13.1"
pip install "google-cloud-storage>=2.13.0"
pip install "google-cloud-translate>=3.12.1"
pip install "gspread-dataframe>=3.3.1"
pip check
pip install "jupyter-console>=6.6.3"
pip install "nbclient>=0.9.0"
pip check
pip install "qtconsole>=5.5.1"
pip install "spacy>=3.7.2"
pip check
# Level 6
# Level 7
pip install "nbconvert>=7.11.0"
pip check
# Level 7
# Level 8
pip install "jupyter-server>=2.10.1"
pip check
# Level 8
# Level 9
pip install "jupyter-lsp>=2.2.0"
pip install "jupyter-server-fileid>=0.9.0"
pip install "jupyterlab-server>=2.25.1"
pip check
pip install "notebook-shim>=0.2.3"
pip check
# Level 9
# Level 10
pip install "jupyter-server-ydoc>=0.8.0"
pip install "jupyterlab>=4.0.8"
pip check
pip install "nbclassic>=1.0.0"
pip check
# Level 10
# Level 11
pip install "notebook>=7.0.6"
pip check
# Level 11
# Level 12
pip install "jupyter>=1.0.0"
pip check
# Level 12
