# 2023-12-28T19:42:33.495403+00:00
# Level 4
pip install "aiodns>=3.1.1"
pip install "aiohttp-cors>=0.7.0"
pip install "aiohttp-socks>=0.8.4"
pip install "alpha-vantage>=2.3.1"
pip install "argon2-cffi>=23.1.0"
pip install "authlib>=1.2.1"
pip install "axial-positional-embedding>=0.2.1"
pip install "azure-eventhub>=5.11.5"
pip install "azure-storage-blob>=12.19.0"
pip check
pip install "bokeh>=3.3.1"
pip install "btrees>=5.1"
pip check
pip install "cmdstanpy>=1.2.0"
pip install "confection>=0.1.3"
pip install "control>=0.9.4"
pip check
pip install "daft>=0.1.2"
pip install "dash>=2.14.1"
pip install "datasets>=2.15.0"
pip install "db-dtypes>=1.1.1"
pip install "descartes>=1.1.0"
pip install "diffusers>=0.23.1"
pip install "distributed>=2023.11.0"
pip check
pip install "etuples>=0.3.9"
pip install "exchange-calendars>=4.5"
pip check
pip install "flask-compress>=1.14"
pip install "folium>=0.15.0"
pip install "fst-pso>=1.8.1"
pip check
pip install "geos>=0.2.3"
pip install "google-api-core>=1.34.0"
pip install "google-auth-httplib2>=0.1.1"
pip install "google-auth-oauthlib>=1.1.0"
pip check
pip install "inflect>=7.0.0"
pip install "invisible-watermark>=0.2.0"
pip install "ipython>=8.17.2"
pip install "isoduration>=20.11.0"
pip check
pip install "jsonschema>=4.20.0"
pip install "keras-vis>=0.4.1"
pip install "keras2onnx>=1.7.0"
pip install "kivy>=2.2.1"
pip install "kivy-examples>=2.2.1"
pip install "kmodes>=0.12.2"
pip check
pip install "librosa>=0.10.1"
pip install "lightfm>=1.17"
pip install "local-attention>=1.9.0"
pip check
pip install "matplotlib-venn>=0.11.9"
pip install "mizani>=0.9.2"
pip install "mlflow>=2.8.1"
pip install "mlxtend>=0.23.0"
pip install "mplfinance>=0.12.8b9"
pip install "msrest>=0.7.1"
pip install "music21>=9.1.0"
pip check
pip install "nilearn>=0.10.2"
pip install "nystrom-attention>=0.0.11"
pip check
pip install "onnx-simplifier>=0.4.35"
pip install "openai>=1.3.2"
pip install "osqp>=0.6.3"
pip check
pip install "paramiko>=3.3.1"
pip install "phik>=0.12.3"
pip install "powerlaw>=1.5"
pip install "proj>=0.2.0"
pip install "prometheus-flask-exporter>=0.23.0"
pip install "py-vollib>=1.0.1"
pip install "pyautogui>=0.9.54"
pip install "pycocotools>=2.0.7"
pip install "pydata-sphinx-theme>=0.13.3"
pip install "pygithub>=2.1.1"
pip check
pip install "pyldavis>=3.4.1"
pip install "pynndescent>=0.5.10"
pip install "pyobjc-framework-accessibility>=10.0"
pip install "pyobjc-framework-applicationservices>=10.0"
pip install "pyobjc-framework-avfoundation>=10.0"
pip install "pyobjc-framework-avkit>=10.0"
pip install "pyobjc-framework-cloudkit>=10.0"
pip install "pyobjc-framework-contactsui>=10.0"
pip install "pyobjc-framework-coreaudiokit>=10.0"
pip install "pyobjc-framework-coreservices>=10.0"
pip check
pip install "pyobjc-framework-coretext>=10.0"
pip install "pyobjc-framework-discrecordingui>=10.0"
pip install "pyobjc-framework-fileproviderui>=10.0"
pip install "pyobjc-framework-gamekit>=10.0"
pip install "pyobjc-framework-instantmessage>=10.0"
pip install "pyobjc-framework-intentsui>=10.0"
pip install "pyobjc-framework-iobluetoothui>=10.0"
pip install "pyobjc-framework-linkpresentation>=10.0"
pip install "pyobjc-framework-localauthentication>=10.0"
pip install "pyobjc-framework-mapkit>=10.0"
pip check
pip install "pyobjc-framework-medialibrary>=10.0"
pip install "pyobjc-framework-metalfx>=10.0"
pip install "pyobjc-framework-metalkit>=10.0"
pip install "pyobjc-framework-metalperformanceshaders>=10.0"
pip install "pyobjc-framework-modelio>=10.0"
pip install "pyobjc-framework-oslog>=10.0"
pip install "pyobjc-framework-quicklookthumbnailing>=10.0"
pip install "pyobjc-framework-safetykit>=10.0"
pip install "pyobjc-framework-scenekit>=10.0"
pip install "pyobjc-framework-screencapturekit>=10.0"
pip check
pip install "pyobjc-framework-securityfoundation>=10.0"
pip install "pyobjc-framework-securityinterface>=10.0"
pip install "pyobjc-framework-sharedwithyou>=10.0"
pip install "pyobjc-framework-spritekit>=10.0"
pip install "pyobjc-framework-syncservices>=10.0"
pip install "pyobjc-framework-usernotificationsui>=10.0"
pip install "pyobjc-framework-videotoolbox>=10.0"
pip install "pyobjc-framework-vision>=10.0"
pip install "pyod>=1.1.1"
pip install "pyopenssl>=23.3.0"
pip check
pip install "pyro-ppl>=1.8.6"
pip install "pytorch-ranger>=0.1.1"
pip check
pip install "qudida>=0.0.4"
pip install "rapids>=0.0.1"
pip check
pip install "s3transfer>=0.7.0"
pip install "scikit-plot>=0.3.7"
pip install "seaborn>=0.13.0"
pip install "secretstorage>=3.3.3"
pip install "seqeval>=1.2.2"
pip install "shap>=0.43.0"
pip install "sklearn>=0.0"
pip install "sklearn-pandas>=2.2.0"
pip install "snapml>=1.14.2"
pip install "sphinx-autobuild>=2021.3.14"
pip check
pip install "sphinx-autodoc-typehints>=1.19.1"
pip install "sphinx-panels>=0.6.0"
pip install "sphinxcontrib-jquery>=4.1"
pip install "stable-baselines3>=2.2.0"
pip install "stanza>=1.6.1"
pip install "statsmodels>=0.14.0"
pip install "stockstats>=0.6.2"
pip install "sweetviz>=2.3.0"
pip check
pip install "tensorflow-datasets>=4.9.3"
pip install "tokenizers>=0.15.0"
pip install "torchmetrics>=1.2.0"
pip install "torchvision>=0.16.1"
pip install "trading-calendars>=2.1.1"
pip install "trio-websocket>=0.11.1"
pip install "tweepy>=4.14.0"
pip check
pip install "vega-datasets>=0.9.0"
pip install "visions>=0.7.5"
pip check
pip install "wandb>=0.16.0"
pip install "wordcloud>=1.9.2"
pip install "wrds>=3.1.6"
pip check
pip install "xarray>=2023.10.1"
pip install "yellowbrick>=1.5"
pip install "yfinance>=0.2.31"
pip check
pip install "zeep>=4.2.1"
pip check
# Level 4
