# 2023-12-28T19:42:33.495403+00:00
# Level 3
pip install "agate>=1.9.0"
pip install "aiohttp>=3.8.6"
pip install "alembic>=1.12.1"
pip install "analytics-python>=1.4.0"
pip install "argon2-cffi-bindings>=21.2.0"
pip install "arrow>=1.3.0"
pip install "astropy>=5.3.4"
pip install "azure-core>=1.29.5"
pip check
pip install "botocore>=1.32.2"
pip install "branca>=0.7.0"
pip install "brotlipy>=0.7.0"
pip install "bs4>=0.0.1"
pip check
pip install "cachecontrol>=0.13.1"
pip install "cairocffi>=1.6.1"
pip install "clarabel>=0.6.0"
pip install "click-repl>=0.3.0"
pip install "coinpaprika>=0.1.0"
pip install "colorcet>=3.0.1"
pip install "comcrawl>=1.0.2"
pip install "cons>=0.4.6"
pip install "coremltools>=7.1"
pip install "croniter>=2.0.1"
pip check
pip install "cryptography>=41.0.5"
pip install "cssselect2>=0.7.0"
pip install "curtsies>=0.4.2"
pip check
pip install "dask>=2023.11.0"
pip install "databricks-cli>=0.18.0"
pip install "datashape>=0.5.2"
pip install "datetime>=5.3"
pip install "datetime-distance>=0.1.3"
pip install "django-cors-headers>=4.3.1"
pip install "django-extensions>=3.2.3"
pip install "django-http-exceptions>=1.4.0"
pip install "django-model-utils>=4.3.1"
pip install "django-request-logging>=0.7.5"
pip check
pip install "djangorestframework>=3.14.0"
pip install "docker>=6.1.3"
pip check
pip install "ecos>=2.0.12"
pip install "elasticsearch>=8.11.0"
pip check
pip install "feather-format>=0.4.1"
pip install "flask>=3.0.0"
pip check
pip install "gdown>=4.7.1"
pip install "gensim>=4.3.2"
pip install "gitpython>=3.1.40"
pip install "google>=3.0.0"
pip install "google-auth>=2.23.4"
pip install "googletransx>=2.4.2"
pip install "gpustat>=1.1.1"
pip install "grpc-google-iam-v1>=0.12.7"
pip install "grpcio-status>=1.48.1"
pip check
pip install "h2o>=3.44.0.2"
pip install "h5netcdf>=1.3.0"
pip install "holidays>=0.36"
pip install "httplib2shim>=0.0.3"
pip install "httpx>=0.25.1"
pip install "huggingface-hub>=0.19.4"
pip install "hyperopt>=0.2.7"
pip check
pip install "ib-insync>=0.9.86"
pip install "imagecodecs-lite>=2022.9.26"
pip install "imagehash>=4.3.1"
pip install "influxdb-client>=1.38.0"
pip install "int-date>=0.2.0"
pip install "intrinio-sdk>=6.26.2"
pip check
pip install "jax>=0.4.20"
pip install "jsonschema-specifications>=2023.11.1"
pip install "jupyter-client>=8.6.0"
pip install "jupyter-packaging>=0.12.3"
pip install "jupyter-server-terminals>=0.4.4"
pip check
pip install "kaggle>=1.5.16"
pip install "kivy-garden>=0.1.5"
pip check
pip install "libcst>=1.1.0"
pip install "lightgbm>=4.1.0"
pip install "luigi>=3.4.0"
pip install "lunarcalendar>=0.0.9"
pip check
pip install "mastodon-py>=1.8.1"
pip install "matplotlib>=3.8.1"
pip install "mdit-py-plugins>=0.4.0"
pip install "miniful>=0.0.6"
pip install "minimal-snowplow-tracker>=0.0.2"
pip install "mixpanel>=4.10.0"
pip install "moviepy>=1.0.3"
pip check
pip install "netcdf4>=1.6.5"
pip install "oauth2client>=4.1.3"
pip install "onnxconverter-common>=1.13.0"
pip install "onnxoptimizer>=0.3.13"
pip install "onnxruntime>=1.16.2"
pip check
pip install "pandas>=2.1.3"
pip install "pathy>=0.10.3"
pip install "persistent>=5.1"
pip install "pettingzoo>=1.24.2"
pip install "pip-tools>=7.3.0"
pip install "pipx>=1.2.1"
pip install "pooch>=1.8.0"
pip install "progressbar2>=4.2.0"
pip install "pyanalyze>=0.11.0"
pip install "pycares>=4.4.0"
pip check
pip install "pydantic>=2.5.1"
pip install "pynacl>=1.5.0"
pip install "pyobjc-framework-accounts>=10.0"
pip install "pyobjc-framework-addressbook>=10.0"
pip install "pyobjc-framework-adservices>=10.0"
pip install "pyobjc-framework-adsupport>=10.0"
pip install "pyobjc-framework-applescriptkit>=10.0"
pip install "pyobjc-framework-applescriptobjc>=10.0"
pip install "pyobjc-framework-apptrackingtransparency>=10.0"
pip install "pyobjc-framework-audiovideobridging>=10.0"
pip check
pip install "pyobjc-framework-authenticationservices>=10.0"
pip install "pyobjc-framework-automaticassessmentconfiguration>=10.0"
pip install "pyobjc-framework-automator>=10.0"
pip install "pyobjc-framework-avrouting>=10.0"
pip install "pyobjc-framework-backgroundassets>=10.0"
pip install "pyobjc-framework-businesschat>=10.0"
pip install "pyobjc-framework-calendarstore>=10.0"
pip install "pyobjc-framework-callkit>=10.0"
pip install "pyobjc-framework-cfnetwork>=10.0"
pip install "pyobjc-framework-classkit>=10.0"
pip check
pip install "pyobjc-framework-collaboration>=10.0"
pip install "pyobjc-framework-colorsync>=10.0"
pip install "pyobjc-framework-contacts>=10.0"
pip install "pyobjc-framework-coreaudio>=10.0"
pip install "pyobjc-framework-corebluetooth>=10.0"
pip install "pyobjc-framework-coredata>=10.0"
pip install "pyobjc-framework-corehaptics>=10.0"
pip install "pyobjc-framework-corelocation>=10.0"
pip install "pyobjc-framework-coremedia>=10.0"
pip install "pyobjc-framework-coremediaio>=10.0"
pip check
pip install "pyobjc-framework-coremidi>=10.0"
pip install "pyobjc-framework-coreml>=10.0"
pip install "pyobjc-framework-coremotion>=10.0"
pip install "pyobjc-framework-corespotlight>=10.0"
pip install "pyobjc-framework-corewlan>=10.0"
pip install "pyobjc-framework-cryptotokenkit>=10.0"
pip install "pyobjc-framework-datadetection>=10.0"
pip install "pyobjc-framework-devicecheck>=10.0"
pip install "pyobjc-framework-discrecording>=10.0"
pip install "pyobjc-framework-diskarbitration>=10.0"
pip check
pip install "pyobjc-framework-dvdplayback>=10.0"
pip install "pyobjc-framework-eventkit>=10.0"
pip install "pyobjc-framework-exceptionhandling>=10.0"
pip install "pyobjc-framework-executionpolicy>=10.0"
pip install "pyobjc-framework-extensionkit>=10.0"
pip install "pyobjc-framework-externalaccessory>=10.0"
pip install "pyobjc-framework-fileprovider>=10.0"
pip install "pyobjc-framework-findersync>=10.0"
pip install "pyobjc-framework-fsevents>=10.0"
pip install "pyobjc-framework-gamecenter>=10.0"
pip check
pip install "pyobjc-framework-gamecontroller>=10.0"
pip install "pyobjc-framework-healthkit>=10.0"
pip install "pyobjc-framework-imagecapturecore>=10.0"
pip install "pyobjc-framework-imserviceplugin>=9.2"
pip install "pyobjc-framework-inputmethodkit>=10.0"
pip install "pyobjc-framework-installerplugins>=10.0"
pip install "pyobjc-framework-intents>=10.0"
pip install "pyobjc-framework-iobluetooth>=10.0"
pip install "pyobjc-framework-iosurface>=10.0"
pip install "pyobjc-framework-ituneslibrary>=10.0"
pip check
pip install "pyobjc-framework-kernelmanagement>=10.0"
pip install "pyobjc-framework-latentsemanticmapping>=10.0"
pip install "pyobjc-framework-mailkit>=10.0"
pip install "pyobjc-framework-mediaaccessibility>=10.0"
pip install "pyobjc-framework-mediatoolbox>=10.0"
pip install "pyobjc-framework-metal>=10.0"
pip install "pyobjc-framework-metrickit>=10.0"
pip install "pyobjc-framework-mlcompute>=10.0"
pip install "pyobjc-framework-multipeerconnectivity>=10.0"
pip install "pyobjc-framework-naturallanguage>=10.0"
pip check
pip install "pyobjc-framework-netfs>=10.0"
pip install "pyobjc-framework-network>=10.0"
pip install "pyobjc-framework-networkextension>=10.0"
pip install "pyobjc-framework-notificationcenter>=10.0"
pip install "pyobjc-framework-opendirectory>=10.0"
pip install "pyobjc-framework-osakit>=10.0"
pip install "pyobjc-framework-passkit>=10.0"
pip install "pyobjc-framework-pencilkit>=10.0"
pip install "pyobjc-framework-photos>=10.0"
pip install "pyobjc-framework-photosui>=10.0"
pip check
pip install "pyobjc-framework-preferencepanes>=10.0"
pip install "pyobjc-framework-pushkit>=10.0"
pip install "pyobjc-framework-quartz>=10.0"
pip install "pyobjc-framework-replaykit>=10.0"
pip install "pyobjc-framework-safariservices>=10.0"
pip install "pyobjc-framework-screensaver>=10.0"
pip install "pyobjc-framework-screentime>=10.0"
pip install "pyobjc-framework-scriptingbridge>=10.0"
pip install "pyobjc-framework-security>=10.0"
pip install "pyobjc-framework-servicemanagement>=10.0"
pip check
pip install "pyobjc-framework-sharedwithyoucore>=10.0"
pip install "pyobjc-framework-shazamkit>=10.0"
pip install "pyobjc-framework-social>=10.0"
pip install "pyobjc-framework-soundanalysis>=10.0"
pip install "pyobjc-framework-speech>=10.0"
pip install "pyobjc-framework-storekit>=10.0"
pip install "pyobjc-framework-systemconfiguration>=10.0"
pip install "pyobjc-framework-systemextensions>=10.0"
pip install "pyobjc-framework-threadnetwork>=10.0"
pip install "pyobjc-framework-uniformtypeidentifiers>=10.0"
pip check
pip install "pyobjc-framework-usernotifications>=10.0"
pip install "pyobjc-framework-videosubscriberaccount>=10.0"
pip install "pyobjc-framework-virtualization>=10.0"
pip install "pyobjc-framework-webkit>=10.0"
pip install "pyperformance>=1.10.0"
pip install "pyramid>=2.0.2"
pip check
pip install "qdldl>=0.1.7"
pip install "requests-cache>=1.1.0"
pip install "requests-file>=1.5.1"
pip install "requests-oauthlib>=1.3.1"
pip install "requests-toolbelt>=1.0.0"
pip install "requests-unixsocket>=0.3.0"
pip install "resampy>=0.4.2"
pip install "responses>=0.24.1"
pip install "rich>=13.7.0"
pip check
pip install "scikit-image>=0.22.0"
pip install "scikit-learn>=1.3.2"
pip install "sclblpy>=0.1.10"
pip install "scs>=3.2.4"
pip install "simpful>=2.11.0"
pip install "soundfile>=0.12.1"
pip install "sparse>=0.14.0"
pip install "spectra>=0.0.11"
pip install "sphinx>=4.5.0"
pip install "stack-data>=0.6.3"
pip check
pip install "starlette>=0.32.0"
pip install "stumpy>=1.12.0"
pip check
pip install "tables>=3.9.1"
pip install "tensorflow-metadata>=1.14.0"
pip install "textblob>=0.17.1"
pip install "tf-keras-vis>=0.8.6"
pip install "tf2onnx>=1.15.1"
pip install "theano>=1.0.5"
pip install "tiingo>=0.14.0"
pip install "torch>=2.1.1"
pip install "trio>=0.23.1"
pip check
pip install "webargs>=8.3.0"
pip install "wikipedia>=1.4.0"
pip check
pip install "xgboost>=2.0.2"
pip install "yahoofinancials>=1.17"
pip check
pip install "zarr>=2.16.1"
pip check
# Level 3
