name: py_env_mini
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.9.7
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
